list: $/tecnotrade/adsbanner/models/banner/columns.yaml
modelClass: Tecnotrade\Adsbanner\Models\Banner
title: Banner
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
filter: config_filter.yaml
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/adsbanner/banner/update/:id'
