list: $/tecnotrade/adsbanner/models/campaignrow/columns.yaml

modelClass: Tecnotrade\Adsbanner\Models\Campaignrow
title: Campaignrow
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
filter: config_filter.yaml
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/adsbanner/campaignrow/update/:id'


