list: $/tecnotrade/adsbanner/models/campaign/columns.yaml
modelClass: Tecnotrade\Adsbanner\Models\Campaign
title: Campaign
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/adsbanner/campaign/update/:id'
