list: $/tecnotrade/adsbanner/models/advertiser/columns.yaml
modelClass: Tecnotrade\Adsbanner\Models\Advertiser
title: Advertiser
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/adsbanner/advertiser/update/:id'
