list: $/tecnotrade/adsbanner/models/site/columns.yaml
modelClass: Tecnotrade\Adsbanner\Models\Site
title: Site
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'tecnotrade/adsbanner/site/update/:id'
